// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "SourceCode.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class SourceCode
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v18.00.01
// App/Edition: SourceCode/
// User:        2sic Web-Developer
// When:        2024-09-09 16:04:54Z
namespace AppCode.Data
{
  // This is a generated class for SourceCode 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// SourceCode data. <br/>
  /// Generated 2024-09-09 16:04:54Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Code`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class SourceCode: AutoGenerated.ZAutoGenSourceCode
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.SourceCode in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenSourceCode: Custom.Data.CustomItem
  {
    /// <summary>
    /// Code as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Code", scrubHtml: true) etc.
    /// </summary>
    public string Code => _item.String("Code", fallback: "");

    /// <summary>
    /// Language as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Language", scrubHtml: true) etc.
    /// </summary>
    public string Language => _item.String("Language", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}